esphome:
  name: "heltec-wl32v3"

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino

#############################################################################    
# Enable logging
logger:
  hardware_uart: UART0

