esphome:
  name: "heltec-wl32v3"
  libraries:
    - "SPI"
    - "Ticker"
    #- RadioLib=https://github.com/jgromes/RadioLib#5.6.0
    #  Other versions break because of the 'chain+' setting in 'library.json' 
    - RadioLib=https://github.com/PaulSchulz/RadioLib


esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino

#############################################################################    
# Enable logging
logger:
  hardware_uart: UART0
  level: DEBUG

#############################################################################
external_components:
  - source:
      type: local
      path: components
    components: [lora_radio]

spi:
  clk_pin: GPIO9
  mosi_pin: GPIO10
  miso_pin: GPIO11
  
lora_radio:
  id: lora_radio_device
  cs_pin: GPIO8


