esphome:
  name: "sensorcap-indicator"

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino

#############################################################################    
# Enable logging
logger:

